# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
from src import bank as module_0


def test_case_0():
    str_0 = "&`^j"
    bank_account_0 = module_0.BankAccount(str_0)
    assert bank_account_0.balance == 0


def test_case_1():
    bool_0 = True
    int_0 = 137
    bank_account_0 = module_0.BankAccount(int_0, int_0)
    var_0 = bank_account_0.withdraw(bool_0)
    assert bank_account_0.balance == 136


def test_case_2():
    bool_0 = False
    int_0 = 137
    bank_account_0 = module_0.BankAccount(int_0, int_0)
    bank_account_0.withdraw(bool_0)


def test_case_3():
    bool_0 = False
    bank_account_0 = module_0.BankAccount(bool_0)
    assert bank_account_0.balance == 0
    bank_account_0.deposit(bool_0)
    bank_account_1 = module_0.BankAccount(bank_account_0)
    assert bank_account_1.balance == 0
    bank_account_1.display_balance()


def test_case_4():
    bool_0 = True
    bank_account_0 = module_0.BankAccount(bool_0)
    assert bank_account_0.balance == 0
    bank_account_0.withdraw(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = True
    bool_1 = False
    none_type_0 = None
    bank_account_0 = module_0.BankAccount(bool_1, none_type_0)
    bank_account_0.deposit(bool_0)
